sudo: required

services:
   - docker

before_install:
  - docker build -t milefanouris/react-test -f ./client/Dockerfile.dev ./client

language: generic

script:
  - docker run -e CI=true milefanouris/react-test npm test

after_success:
  - docker build -t milefanouris/multi-client ./client
  - docker build -t milefanouris/multi-nginx ./nginx
  - docker build -t milefanouris/multi-server ./server
  - docker build -t milefanouris/multi-worker ./worker
  #Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
  - docker push milefanouris/multi-client
  - docker push milefanouris/multi-nginx
  - docker push milefanouris/multi-server
  - docker push milefanouris/multi-worker